use_frameworks!

platform :ios, '8.0'

target 'ZJScrollPageView-wb_Example' do
  pod 'ZJScrollPageView-wb', :path => '../'

  target 'ZJScrollPageView-wb_Tests' do
    inherit! :search_paths

    
  end
end
